### ISSUE TITLE
Nice Work

### ISSUE THREAD

**Issue by rahulkapoor90** [VITUni/List#1]
Why @itsN1X copied my whole [gist](https://gist.github.com/rahulkapoor90/1acba95b58a70ad9d4aa)?

**Comment by itsN1X** [comment]
its better this  way, right?
 : )

**Comment by rahulkapoor90** [comment]
what?? let me tell you don't get to copy other's work and then even  say "it's better this way, right?"

**Comment by itsN1X** [comment]
:lol
i mean _it **looks** better this way, right?_
